apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
        - name: memory-hog
          image: python:3.12-alpine
          command:
            - python
            - -c
            - |
              x = []
              while True:
                  x.append("X" * 1024 * 1024)
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"