apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-app
  template:
    metadata:
      labels:
        app: broken-app
    spec:
      containers:
        - name: broken-app
          image: busybox
          command: ["sh", "-c", "echo DATABASE_CONNECTION_FAILED; exit 2"]
